# Graph-focused config
shown_boxes = "cpu mem net"
graph_symbol = "braille"
graph_symbol_cpu = "braille"
graph_symbol_mem = "braille"
graph_symbol_net = "braille"
cpu_size = 33
cpu_single_graph = True
mem_graphs = True
show_swap = False
net_auto = True
update_ms = 1000
rounded_corners = True
